kind: pipeline
name: default

workspace:
  path: /source

steps:
  - name: build
    image: plugins/docker
    settings:
      username: p01
      password:
        from_secret: P01_DOCKER_PASSWORD
      repo: p01/socat
      tags:
        - latest

trigger:
  branch:
    - master
